How to build a custom CSV importer in farmOS (video)
farmOS/farmOS-community-blog pull request #26
Opened 2024-03-23 09:53 UTC by mstenta

2024-03-25 09:27 UTC, pcambra approved these changes, later dismissed

2024-03-25 11:52 UTC, wotnak requested changes

2024-03-25 11:52 UTC, wotnak commented on posts/2024/how-to-custom-csv-importer-video/index.md
> +do, that is possible in a custom module. farmOS leverage's Drupal's Migrate API
```suggestion
do, that is possible in a custom module. farmOS leverages Drupal's Migrate API
```

2024-03-25 11:52 UTC, wotnak commented on posts/2024/how-to-custom-csv-importer-video/index.md
> +All of the documentation and resources referenced in this video is available at
```suggestion
All of the documentation and resources referenced in this video are available at
```

2024-03-27 09:55 UTC, mstenta commented
Thanks for the reviews @pcambra @wotnak!

I've fixed the grammatical errors and force pushed.

I also changed the directory path from `how-to-custom-csv-importer-video` to `how-to-build-custom-csv-importer-video` (added `build`). Maybe slightly better for SEO? Looks better to a human at least, IMO. :-)

Ready for re-review!

2024-03-27 10:03 UTC, wotnak approved these changes

2024-03-27 10:05 UTC, merged